# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

align_sequences_cpp <- function(reference_file, query_seqs, query_names, query_quals, preset = "map-ont", n_threads = 3L) {
    .Call(`_minimap2_align_sequences_cpp`, reference_file, query_seqs, query_names, query_quals, preset, n_threads)
}

