# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_index_cpp <- function(fn_idx_in, preset, k, w, min_cnt, min_chain_score, bw, n_threads) {
    .Call(`_minimap2_build_index_cpp`, fn_idx_in, preset, k, w, min_cnt, min_chain_score, bw, n_threads)
}

align_sequences_cpp <- function(idx_ptr, query_seq, query_name, cs, MD) {
    .Call(`_minimap2_align_sequences_cpp`, idx_ptr, query_seq, query_name, cs, MD)
}

destroy_index_cpp <- function(idx_ptr) {
    invisible(.Call(`_minimap2_destroy_index_cpp`, idx_ptr))
}

