# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_index_cpp <- function(reference_file, preset, n_threads) {
    .Call(`_minimap2_build_index_cpp`, reference_file, preset, n_threads)
}

align_sequences_cpp <- function(reference_file, query_seqs, query_names, query_quals, preset = "map-ont", n_threads = 3L) {
    .Call(`_minimap2_align_sequences_cpp`, reference_file, query_seqs, query_names, query_quals, preset, n_threads)
}

aligner_map_cpp <- function(mi_ptr, query_seqs, query_names, query_quals) {
    .Call(`_minimap2_aligner_map_cpp`, mi_ptr, query_seqs, query_names, query_quals)
}

